# Generated by Django 3.2.9 on 2021-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeaProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('time', models.TimeField(null=True, verbose_name='Time')),
                ('precip', models.FloatField(default=None, verbose_name='Precipitation')),
                ('temp', models.FloatField(default=None, verbose_name='Temperature')),
                ('rh', models.FloatField(default=None, verbose_name='RelativeHumidity')),
                ('press', models.FloatField(default=None, verbose_name='pressure')),
                ('wspd', models.FloatField(default=None, verbose_name='windSpeed')),
                ('wdir', models.IntegerField(default=None, verbose_name='windDirection')),
                ('gamma', models.IntegerField(default=None, verbose_name='Gamma')),
                ('radon', models.FloatField(default=None, verbose_name='Radon')),
            ],
            options={
                'verbose_name': ('Sea Properties',),
                'verbose_name_plural': 'Sea Properties',
                'ordering': ['date', 'time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('record', models.ManyToManyField(to='db.SeaProperties', verbose_name='SeaProperties')),
            ],
            options={
                'verbose_name': ('My Dataset',),
                'verbose_name_plural': 'My Datasets',
                'ordering': ['name', 'id'],
            },
        ),
    ]
